name = "fs-idx-edge"
main = "worker.js"
compatibility_date = "2026-05-08"
compatibility_flags = ["nodejs_compat"]

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "95d21fb829ce4edfbd0a68484e3240fd"

[vars]
R2_PUBLIC_URL = "https://media.foursailsrealestate.com"

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = false

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true
